export const Images = {
  AUTH_BACKGROUND: require('../../assets/images/auth-background.jpg'),
  LOGIN_LOGO: require('../../assets/images/login-logo.png'),
  USER: require('../../assets/icons/user.png'),
  KEY: require('../../assets/icons/key.png'),
  CHAT: require('../../assets/icons/chat.png'),
  GROUP: require('../../assets/icons/group.png'),
  HOME: require('../../assets/icons/home.png'),
  POWER: require('../../assets/icons/power-off.png'),
  MAIN_LOGO: require('../../assets/images/main-logo.png'),
  USER_AVATAR: require('../../assets/icons/user-avatar.png'),
  UP: require('../../assets/icons/up.png'),
  DOWN: require('../../assets/icons/down.png'),
  FAV: require('../../assets/images/fav.png'),
  BIRTHDAY: require('../../assets/images/birthday.png'),
  FOOD_MENU: require('../../assets/images/food-menu.png'),
  SEACRH: require('../../assets/icons/search.png'),
  CLOSE: require('../../assets/icons/close.png'),
  BACK: require('../../assets/icons/back.png'),
  BUS: require('../../assets/images/bus.png'),
  PDF: require('../../assets/images/createpdf.png'),
  TRASH: require('../../assets/icons/trash-bin.png'),
  BACK_SLIDER: require('../../assets/icons/back-slider.png'),
  ARROW: require('../../assets/icons/right-arrow.png'),
  HAIR_DRESSER: '../../assets/icons/scissors.png',
};

export const Animations = {
  LOCATION: require('../../assets/animations/location.json'),
};
